version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  api:
    build: .
    restart: always
    command: ./manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/api
    ports:
      - "8001:8000"
    depends_on:
      - db
