# Generated by Django 4.1.2 on 2022-10-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('published_time', models.DateTimeField()),
                ('headline', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True)),
                ('related', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
